<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class StaffSeeder extends Seeder
{
  public function run(): void
  {
    // Original staff array
    $staff = [
      [
        'name' => 'Juliana Ahmadu',
        'email' => 'JulianaAhmadu@ophthalcare.com',
        'phone' => '8030978350',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Amaka Aladiuba',
        'email' => 'AmakaAladiuba@ophthalcare.com',
        'phone' => '8032874966',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Martina Ulluwo',
        'email' => 'MartinaUlluwo@ophthalcare.com',
        'phone' => '7083534629',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Charity Yakubu',
        'email' => 'CharityYakubu@ophthalcare.com',
        'phone' => '8035943753',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Halimatu Aliyu',
        'email' => 'HalimatuAliyu@ophthalcare.com',
        'phone' => '8036015832',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Haruna Jemimah Yakubu',
        'email' => 'HarunaJemimah Yakubu@ophthalcare.com',
        'phone' => '8084524110',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Hannatu Isyaku',
        'email' => 'HannatuIsyaku@ophthalcare.com',
        'phone' => '8135619088',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Patience Haruna Yakuba',
        'email' => 'PatienceHaruna Yakuba@ophthalcare.com',
        'phone' => '8130713943',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Gloria Tenkorang',
        'email' => 'GloriaTenkorang@ophthalcare.com',
        'phone' => '7061280130',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Comfort Adamgbe',
        'email' => 'ComfortAdamgbe@ophthalcare.com',
        'phone' => '8137086833',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Helen Gimba',
        'email' => 'HelenGimba@ophthalcare.com',
        'phone' => '8102214336',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Blessing Joseph Akogwu',
        'email' => 'BlessingJoseph Akogwu@ophthalcare.com',
        'phone' => '7068011819',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'NNOROM CHIZOMA',
        'email' => 'NNOROMCHIZOMA@ophthalcare.com',
        'phone' => '9035222661',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Sonia Joseph-Okogun',
        'email' => 'SoniaJoseph-Okogun@ophthalcare.com',
        'phone' => '8168302460',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Godiya Garba Rabo',
        'email' => 'GodiyaGarba Rabo@ophthalcare.com',
        'phone' => '8163260466',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Esther Samuel',
        'email' => 'EstherSamuel@ophthalcare.com',
        'phone' => '8058556514',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Mercy Bolaji',
        'email' => 'MercyBolaji@ophthalcare.com',
        'phone' => '8104237676',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Martha Okoh',
        'email' => 'MarthaOkoh@ophthalcare.com',
        'phone' => '8062060233',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Nagarta Zidon',
        'email' => 'NagartaZidon@ophthalcare.com',
        'phone' => '8067041085',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Maryam Jegede',
        'email' => 'MaryamJegede@ophthalcare.com',
        'phone' => '8028313062',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Salamatu Christopher',
        'email' => 'SalamatuChristopher@ophthalcare.com',
        'phone' => '8085219744',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Maryamu Daniel',
        'email' => 'MaryamuDaniel@ophthalcare.com',
        'phone' => '8036082394',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Precious Egwuonwu',
        'email' => 'PreciousEgwuonwu@ophthalcare.com',
        'phone' => '8035132268',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Maryamu Yusuf',
        'email' => 'MaryamuYusuf@ophthalcare.com',
        'phone' => '8131643451',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Shamsiyya Umar Yakubu',
        'email' => 'ShamsiyyaUmar Yakubu@ophthalcare.com',
        'phone' => '8031864268',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Murna Luka',
        'email' => 'MurnaLuka@ophthalcare.com',
        'phone' => '8065715572',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Saignom Banda

',
        'email' => 'SaignomBanda@ophthalcare.com',
        'phone' => '7068264306',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Mariya Yahaya',
        'email' => 'MariyaYahaya@ophthalcare.com',
        'phone' => '7082464696',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Joy Nwachukwu',
        'email' => 'JoyNwachukwu@ophthalcare.com',
        'phone' => '8062075706',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Ngozi O Elebo',
        'email' => 'NgoziO Elebo@ophthalcare.com',
        'phone' => '8065577750',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Christiana Rumbu',
        'email' => 'ChristianaRumbu@ophthalcare.com',
        'phone' => '8039796529',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'MARIAM DANDO',
        'email' => 'MARIAMDANDO@ophthalcare.com',
        'phone' => '8169892968',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Halima Yakubu Musa',
        'email' => 'HalimaYakubu Musa@ophthalcare.com',
        'phone' => '8166132710',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Gabriella Godfrey',
        'email' => 'GabriellaGodfrey@ophthalcare.com',
        'phone' => '8169467215',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'MARYAM ISIAKU',
        'email' => 'MARYAMISIAKU@ophthalcare.com',
        'phone' => '9030585203',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Ijanada Philip',
        'email' => 'IjanadaPhilip@ophthalcare.com',
        'phone' => '7035582661',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Rosemary Ebinum',
        'email' => 'RosemaryEbinum@ophthalcare.com',
        'phone' => '7065013367',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Habiba Barau',
        'email' => 'HabibaBarau@ophthalcare.com',
        'phone' => '7036676751',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Sarah Evans',
        'email' => 'SarahEvans@ophthalcare.com',
        'phone' => '8033904030',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Shade Oyetunji',
        'email' => 'ShadeOyetunji@ophthalcare.com',
        'phone' => '8030522660',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'COMFORT OBAYEMI',
        'email' => 'COMFORTOBAYEMI@ophthalcare.com',
        'phone' => '8034722628',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Ronke Samuel',
        'email' => 'RonkeSamuel@ophthalcare.com',
        'phone' => '7030412824',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Sarah Malomo',
        'email' => 'SarahMalomo@ophthalcare.com',
        'phone' => '8062148206',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Ruth Adeyemo',
        'email' => 'RuthAdeyemo@ophthalcare.com',
        'phone' => '8063874193',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Tabitha Ezekiel',
        'email' => 'TabithaEzekiel@ophthalcare.com',
        'phone' => '7032904531',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Opeyemi Jegede',
        'email' => 'OpeyemiJegede@ophthalcare.com',
        'phone' => '8033652031',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'HANNAH ALEGBEJO',
        'email' => 'HANNAHALEGBEJO@ophthalcare.com',
        'phone' => '8051732661',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Jummai Yakubu',
        'email' => 'JummaiYakubu@ophthalcare.com',
        'phone' => '8065039271',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Aisha Isah',
        'email' => 'AishaIsah@ophthalcare.com',
        'phone' => '7068740715',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Rahab Benard',
        'email' => 'RahabBenard@ophthalcare.com',
        'phone' => '8131040068',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'COMFORT REUBEN',
        'email' => 'COMFORTREUBEN@ophthalcare.com',
        'phone' => '8030696023',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Hauwa Yusuf',
        'email' => 'HauwaYusuf@ophthalcare.com',
        'phone' => '7085527939',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Anthonia N.A.',
        'email' => 'AnthoniaN.A.@ophthalcare.com',
        'phone' => '8050793893',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Hannatu Yarang',
        'email' => 'HannatuYarang@ophthalcare.com',
        'phone' => '8138575891',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Martha Musa',
        'email' => 'MarthaMusa@ophthalcare.com',
        'phone' => '8105088579',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Afiniki Simon',
        'email' => 'AfinikiSimon@ophthalcare.com',
        'phone' => '7061528353',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Pauline Ikwuakolam',
        'email' => 'PaulineIkwuakolam@ophthalcare.com',
        'phone' => '8032691270',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Victoria Ikechukwu',
        'email' => 'VictoriaIkechukwu@ophthalcare.com',
        'phone' => '8038112821',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Yock Saidu',
        'email' => 'YockSaidu@ophthalcare.com',
        'phone' => '80687170',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Jennifer Dashe',
        'email' => 'JenniferDashe@ophthalcare.com',
        'phone' => '8059395117',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Biodun Ehiaze',
        'email' => 'BiodunEhiaze@ophthalcare.com',
        'phone' => '8034537183',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Helen Akolo',
        'email' => 'HelenAkolo@ophthalcare.com',
        'phone' => '8081264533',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Rhoda Ishaya',
        'email' => 'RhodaIshaya@ophthalcare.com',
        'phone' => '7083393839',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Adeola Bolaji',
        'email' => 'AdeolaBolaji@ophthalcare.com',
        'phone' => '8030779280',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'HOSSANA EMMANUEL',
        'email' => 'HOSSANAEMMANUEL@ophthalcare.com',
        'phone' => '8060063119',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Mercy Maichibi',
        'email' => 'MercyMaichibi@ophthalcare.com',
        'phone' => '7037718479',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Sunday Abuh',
        'email' => 'SundayAbuh@ophthalcare.com',
        'phone' => '8060297605',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Lazarus Iliya',
        'email' => 'LazarusIliya@ophthalcare.com',
        'phone' => '7033279527',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Micah Sabo',
        'email' => 'MicahSabo@ophthalcare.com',
        'phone' => '8031959271',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Jeremiah Adama',
        'email' => 'JeremiahAdama@ophthalcare.com',
        'phone' => '8062772064',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Daniel Jonah Akubo',
        'email' => 'DanielJonah Akubo@ophthalcare.com',
        'phone' => '8100178084',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Gloria Anche',
        'email' => 'GloriaAnche@ophthalcare.com',
        'phone' => '8028338617',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Maikudi Ayuba',
        'email' => 'MaikudiAyuba@ophthalcare.com',
        'phone' => '7038767807',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Jeremiah Johnson',
        'email' => 'JeremiahJohnson@ophthalcare.com',
        'phone' => '7039456238',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Augustine Etoh',
        'email' => 'AugustineEtoh@ophthalcare.com',
        'phone' => '8031990781',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Murtala Abdu',
        'email' => 'MurtalaAbdu@ophthalcare.com',
        'phone' => '8069129259',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'EMMANUEL OTOMI',
        'email' => 'EMMANUELOTOMI@ophthalcare.com',
        'phone' => '8033446366',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'YUSUF SALISU YAKUBU',
        'email' => 'YUSUFSALISU YAKUBU@ophthalcare.com',
        'phone' => '8023106455',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Bulus Sunday',
        'email' => 'BulusSunday@ophthalcare.com',
        'phone' => '7031001721',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Cyrus James',
        'email' => 'CyrusJames@ophthalcare.com',
        'phone' => '8139392814',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Ibrahim Mataka',
        'email' => 'IbrahimMataka@ophthalcare.com',
        'phone' => '7060521870',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Lucky Efajemue',
        'email' => 'LuckyEfajemue@ophthalcare.com',
        'phone' => '8032290684',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Augustine Etoh',
        'email' => 'AugustineEtoh@ophthalcare.com',
        'phone' => '8113604709',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'SIMON WADA',
        'email' => 'SIMONWADA@ophthalcare.com',
        'phone' => '8037878157',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Robert Elisha',
        'email' => 'RobertElisha@ophthalcare.com',
        'phone' => '8166005764',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Danlami Abdu Bako',
        'email' => 'DanlamiAbdu Bako@ophthalcare.com',
        'phone' => '8161564316',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Usman Yohanna',
        'email' => 'UsmanYohanna@ophthalcare.com',
        'phone' => '8065463297',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Zamani Ishaya',
        'email' => 'ZamaniIshaya@ophthalcare.com',
        'phone' => '7030639577',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'MELCHIZEDEK IGNATIUS MUNAJE',
        'email' => 'MELCHIZEDEK IGNATIUSMUNAJE@ophthalcare.com',
        'phone' => '8088252366',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Ahmed Hudu',
        'email' => 'AhmedHudu@ophthalcare.com',
        'phone' => '8069510287',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'oyeronke KOMOLAFE',
        'email' => 'oyeronkeKOMOLAFE@ophthalcare.com',
        'phone' => '8035865229',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Ugbede Idakwo',
        'email' => 'UgbedeIdakwo@ophthalcare.com',
        'phone' => '8036370768',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Ibrahim David',
        'email' => 'IbrahimDavid@ophthalcare.com',
        'phone' => '8058217247',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Inusa Dauda',
        'email' => 'InusaDauda@ophthalcare.com',
        'phone' => '8085861209',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Ishaya Iliya',
        'email' => 'IshayaIliya@ophthalcare.com',
        'phone' => '7068036268',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Dogara Auta',
        'email' => 'DogaraAuta@ophthalcare.com',
        'phone' => '7065640390',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Douglas Pam',
        'email' => 'DouglasPam@ophthalcare.com',
        'phone' => '8168725756',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Solomon Namo',
        'email' => 'SolomonNamo@ophthalcare.com',
        'phone' => '8063217263',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Suleiman Umar',
        'email' => 'SuleimanUmar@ophthalcare.com',
        'phone' => '8069925442',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Michael Ajolomufiah',
        'email' => 'MichaelAjolomufiah@ophthalcare.com',
        'phone' => '7035996500',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Mordecai Wushangka',
        'email' => 'MordecaiWushangka@ophthalcare.com',
        'phone' => '7038364628',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Jeremiah Mamtara',
        'email' => 'JeremiahMamtara@ophthalcare.com',
        'phone' => '8065416445',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'John Ebong',
        'email' => 'JohnEbong@ophthalcare.com',
        'phone' => '8166421953',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Joseph Monday',
        'email' => 'JosephMonday@ophthalcare.com',
        'phone' => '7065481185',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Mugana Ishaya',
        'email' => 'MuganaIshaya@ophthalcare.com',
        'phone' => '8070884458',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Joseph Dahiru',
        'email' => 'JosephDahiru@ophthalcare.com',
        'phone' => '8035629969',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'ThankGod Bulus',
        'email' => 'ThankGodBulus@ophthalcare.com',
        'phone' => '7030149217',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Yahaya Bako',
        'email' => 'YahayaBako@ophthalcare.com',
        'phone' => '8130320937',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Juliefaith Samuel',
        'email' => 'JuliefaithSamuel@ophthalcare.com',
        'phone' => '7061946450',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Stephen Nubobga',
        'email' => 'StephenNubobga@ophthalcare.com',
        'phone' => '8028394011',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Sani Yunusa',
        'email' => 'SaniYunusa@ophthalcare.com',
        'phone' => '8068160999',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Mato Danladi',
        'email' => 'MatoDanladi@ophthalcare.com',
        'phone' => '7015719557',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Musa Bukar',
        'email' => 'MusaBukar@ophthalcare.com',
        'phone' => '7035586305',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Silas Nomba',
        'email' => 'SilasNomba@ophthalcare.com',
        'phone' => '8029170395',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Yakubu Mohammed',
        'email' => 'YakubuMohammed@ophthalcare.com',
        'phone' => '8034758796',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Ayuba Wada',
        'email' => 'AyubaWada@ophthalcare.com',
        'phone' => '8058891150',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Samuel Medeludo',
        'email' => 'SamuelMedeludo@ophthalcare.com',
        'phone' => '8011223344',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Lazarus Ayuba',
        'email' => 'LazarusAyuba@ophthalcare.com',
        'phone' => '8039641846',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'ABDULLAHI EMMANUEL SIMEON',
        'email' => 'ABDULLAHIEMMANUEL SIMEON@ophthalcare.com',
        'phone' => '8051372154',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Samaila Ahmed',
        'email' => 'SamailaAhmed@ophthalcare.com',
        'phone' => '9070730828',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Aanuoluwa Olusegun',
        'email' => 'AanuoluwaOlusegun@ophthalcare.com',
        'phone' => '8167456274',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Jeremiah Jones',
        'email' => 'JeremiahJones@ophthalcare.com',
        'phone' => '8162472333',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Jude Nubuya',
        'email' => 'JudeNubuya@ophthalcare.com',
        'phone' => '7062233825',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'KENNETH UKUMOBE',
        'email' => 'KENNETHUKUMOBE@ophthalcare.com',
        'phone' => '8077779429',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Isaac Modibbo',
        'email' => 'IsaacModibbo@ophthalcare.com',
        'phone' => '8163447577',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Yahaya Maijama\'a Abdu',
        'email' => 'YahayaMaijama\'a Abdu@ophthalcare.com',
        'phone' => '9059143107',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Danjuma Maiwada',
        'email' => 'DanjumaMaiwada@ophthalcare.com',
        'phone' => '7032906995',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Dauda Irmiya',
        'email' => 'DaudaIrmiya@ophthalcare.com',
        'phone' => '8085183997',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'SHEMIYA YOHANNA',
        'email' => 'SHEMIYAYOHANNA@ophthalcare.com',
        'phone' => '8061278170',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Olalekan Ogundare',
        'email' => 'OlalekanOgundare@ophthalcare.com',
        'phone' => '7034661708',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Bobga Bala',
        'email' => 'BobgaBala@ophthalcare.com',
        'phone' => '7063395453',
        'password' => Hash::make('password'),
        'created_at' => now(),
        'updated_at' => now(),
      ]
    ];

    // Process the staff array to split names
    $processedStaff = array_map(function ($employee) {
      // Split the name by the last space
      $nameParts = explode(' ', trim($employee['name']));
      $lastname = array_pop($nameParts); // Last part as lastname
      $firstname = implode(' ', $nameParts); // Join remaining parts as firstname

      // Handle edge cases
      if (empty($firstname)) {
        $firstname = $lastname; // If no firstname, use lastname
        $lastname = '';
      }

      // Normalize case (e.g., convert "NNOROM CHIZOMA" to "Nnorom Chizoma")
      $firstname = ucwords(strtolower($firstname));
      $lastname = ucwords(strtolower($lastname));

      return [
        'firstname' => $firstname,
        'lastname' => $lastname,
        'email' => $employee['email'],
        'phone' => $employee['phone'],
        'password' => $employee['password'],
        'created_at' => $employee['created_at'],
        'updated_at' => $employee['updated_at'],
      ];
    }, $staff);

    // Insert into the users table
    DB::table('users')->insert($processedStaff);
  }
}
