<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Refraction extends Model
{
    use HasFactory;

  protected $fillable = [
    'patient_id',
    'itching_right',
    'itching_left',
    'photophobia_right',
    'photophobia_left',
    'pain_right',
    'pain_left',
    'blur_vision_far_right',
    'blur_vision_far_left',
    'blur_vision_near_right',
    'blur_vision_near_left',
    'diplopia_right',
    'diplopia_left',
    'burning_sensation_right',
    'burning_sensation_left',
    'tearing_right',
    'tearing_left',
    'discharge_right',
    'discharge_left',
    'occipital_headache',
    'frontal_headache',
    'temporal_headache',
    'hypertensive',
    'diabetic',
    'adnexa_right',
    'adnexa_left',
    'conjuctiva_right',
    'conjuctiva_left',
    'sclera_right',
    'sclera_left',
    'pupil_right',
    'pupil_left',
    'palpebra_right',
    'palpebra_left',
    'cornea_right',
    'cornea_left',
    'distance_right',
    'distance_left',
    'ph_right',
    'ph_left',
    'near_right',
    'near_left',
    'sph_glass_right',
    'sph_glass_left',
    'cyl_glass_right',
    'cyl_glass_left',
    'axis_glass_right',
    'axis_glass_left',
    'prism_glass_right',
    'prism_glass_left',
    'base_glass_right',
    'base_glass_left',
    'va_glass_right',
    'va_glass_left',
    'add_glass_right',
    'add_glass_left',
    'va2_glass_right',
    'va2_glass_left',
    'auto_refraction_right',
    'auto_refraction_left',
    'va_auto_right',
    'va_auto_left',
    'sph_retino_right',
    'sph_retino_left',
    'cyl_retino_right',
    'cyl_retino_left',
    'axis_retino_right',
    'axis_retino_left',
    'prism_retino_right',
    'prism_retino_left',
    'base_retino_right',
    'base_retino_left',
    'va_retino_right',
    'va_retino_left',
    'sph_subj_right',
    'sph_subj_left',
    'cyl_subj_right',
    'cyl_subj_left',
    'axis_subj_right',
    'axis_subj_left',
    'prism_subj_right',
    'prism_subj_left',
    'base_subj_right',
    'base_subj_left',
    'va_subj_right',
    'va_subj_left',
    'add_subj_right',
    'add_subj_left',
    'va2_subj_right',
    'va2_subj_left',
    'diagnosis',
    'additional_info',
    'user_id',
  ];

  public function user()
  {
    return $this->belongsTo(User::class);
  }
}

